In [1]:
import numpy as np

### `Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [6]:
q1arr = np.array([  [92, 90, 74],
                    [6, 63, 93],
                    [15, 93, 96],
                    [70, 60, 48]])
q1arr

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [4]:
np.sort(q1arr, axis=1)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [9]:
q1arr[q1arr[:,1].argsort()]

array([[70, 60, 48],
       [ 6, 63, 93],
       [92, 90, 74],
       [15, 93, 96]])

In [ ]:
np.array(sorted(arr, key = lambda x: max(x)))

In [40]:
sorted(q1arr, key=lambda x: max(x))

[array([70, 60, 48]),
 array([92, 90, 74]),
 array([ 6, 63, 93]),
 array([15, 93, 96])]

In [11]:
np.sort(q1arr, axis=None).reshape(4,3)

array([[ 6, 15, 48],
       [60, 63, 70],
       [74, 90, 92],
       [93, 93, 96]])

### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [46]:
marks = np.array([   [13, 10,  9, 33],
                     [63, 46, 90, 42],
                     [39, 76, 13, 29],
                     [82,  9, 29, 78],
                     [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92])
#Two extra students record-
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

In [47]:
extra_subject=np.expand_dims(extra_subject, axis=1)
extra_subject

array([[41],
       [87],
       [72],
       [36],
       [92]])

In [48]:
marks=np.concatenate((marks,extra_subject), axis=1)
display(marks)

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [49]:
rec1=np.expand_dims(rec1, axis=0)
rec2=np.expand_dims(rec2, axis=0)

In [50]:
total_marks=np.concatenate((marks,rec1, rec2), axis=0)
total_marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [56]:
total_sum=np.sum(total_marks, axis=1)
total_sum=np.expand_dims(total_sum, axis=1)
total_marks=np.concatenate((total_marks,total_sum), axis=1)
total_marks

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [57]:
sorted(total_marks, key= lambda x : max(x))[::-1]

[array([ 77,  83,  98,  95,  89, 442]),
 array([ 92,  71,  52,  61,  53, 329]),
 array([ 63,  46,  90,  42,  87, 328]),
 array([ 67,  61,  59,  36,  92, 315]),
 array([ 82,   9,  29,  78,  36, 234]),
 array([ 39,  76,  13,  29,  72, 229]),
 array([ 13,  10,   9,  33,  41, 106])]

### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [59]:
q3arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

display(np.unique(q3arr, axis=0))
display(np.unique(q3arr, axis=1))

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

### `Q-4:` Flip given 2-D array along both axes at the same time.

In [60]:
q4arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
np.flip(q4arr, axis=[0,1])

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [66]:
arr = np.array(
     [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

X = 6
mask=arr>X
np.where(np.any(mask, axis=1))[0]

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [68]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [69]:
np.concatenate([arr1,arr2,arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [76]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
max_index=np.where(arr==arr.max())
min_index=np.where(arr==arr.min())

arr=np.delete(arr, max_index)
arr=np.delete(arr, min_index)
arr

array([418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458, 387, 262,
       613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967, 277, 470,
       336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592, 997, 137,
       340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932, 645, 952,
       921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251, 957, 103,
       920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244, 782, 763,
       635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270, 308, 231,
       952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320, 230, 324,
       922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587, 227, 853,
       757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879, 575, 936,
       705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395, 525, 922,
       136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976, 786, 235,
       930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621, 453, 193,
       607, 677, 637, 728, 724, 534, 748, 291, 194, 761, 875, 68

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [83]:
q8arr=np.random.randint(100, 700, size=(20))
q8arr

array([340, 649, 456, 632, 544, 413, 131, 544, 232, 482, 410, 532, 471,
       405, 100, 674, 218, 153, 146, 261])

In [88]:
q8arr[np.where(q8arr>200)]=200

In [89]:
q8arr

array([200, 200, 200, 200, 200, 200, 131, 200, 200, 200, 200, 200, 200,
       200, 100, 200, 200, 153, 146, 200])

In [90]:
np.sort(q8arr)

array([100, 131, 146, 153, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200])

In [91]:
np.cumsum(q8arr)

array([ 200,  400,  600,  800, 1000, 1200, 1331, 1531, 1731, 1931, 2131,
       2331, 2531, 2731, 2831, 3031, 3231, 3384, 3530, 3730])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [94]:
q9arr=np.random.random(10)
q9arr=np.around(q9arr, decimals=3)
q9arr

array([0.288, 0.582, 0.707, 0.964, 0.855, 0.495, 0.397, 0.201, 0.607,
       0.879])

In [96]:
np.percentile(q9arr,0)==q9arr.min()

True

In [97]:
np.percentile(q9arr,100)==q9arr.max()

True

In [98]:
np.percentile(q9arr, 51)-np.percentile(q9arr, 50)

0.0022499999999999742