In [2]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
q1arr=np.zeros(10)
q1arr[4]=1
q1arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [4]:
a=int(input())
b=int(input())

q2arr=np.random.random((a,b))

display(q2arr)
display("column wise --> " + str(np.mean(q2arr, axis=0)))
display("row wise --> " + str(np.mean(q2arr, axis=1)))

array([[0.85711057, 0.53274859, 0.85769102],
       [0.80748071, 0.67074672, 0.04462439]])

'column wise --> [0.83229564 0.60174765 0.4511577 ]'

'row wise --> [0.74918339 0.50761727]'

### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [5]:
a=int(input())
b=int(input())

q3arr=np.zeros((a,b))
display("2d array")
display(q3arr)

q3arr[:,0]=1
q3arr[0,:]=1
q3arr[:,-1]=1
q3arr[-1,:]=1

display("modified 2d array")
display(q3arr)


'2d array'

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

'modified 2d array'

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [6]:
q4arr=np.linspace(0,1,12)[1:-1]
display(q4arr)

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [7]:
q5arr=np.eye(3,4)
display(q5arr)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [8]:
q6arr=np.linspace(0,4,25)
q6arr.reshape(5,5)

array([[0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667],
       [0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ],
       [1.66666667, 1.83333333, 2.        , 2.16666667, 2.33333333],
       [2.5       , 2.66666667, 2.83333333, 3.        , 3.16666667],
       [3.33333333, 3.5       , 3.66666667, 3.83333333, 4.        ]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [9]:
random_vector=np.random.randint(1,101,20).reshape(10,2)

In [10]:
point = np.array([2,3])

In [11]:
ans=random_vector-point
ans=ans**2
ans=np.sum(ans, axis=1)
display(np.sqrt(ans))

array([102.88342918,  41.77319715,  57.7754273 ,   9.21954446,
        66.09841148,  53.15072906,  64.40496875,  78.84795495,
       104.78549518,  85.38149682])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [30]:
q8arr=np.random.random((6,7,8))
tofind=q8arr.ravel()[99]
np.where(q8arr==tofind)

(array([1]), array([5]), array([3]))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [31]:
inputarr=np.array([1, 2, 3, 4, -8, -10])
display(inputarr[::-1])

array([-10,  -8,   4,   3,   2,   1])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [33]:
input_array=np.array([1])
input_array2=np.array([1,2,3,4])

display(len(input_array))
display(len(input_array2))

1

4

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [39]:
def softmax(arr):
    return np.exp(arr)/np.sum(np.exp(arr))

In [40]:
q11arr=np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])
q11arr2=np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])

display(softmax(q11arr))
display(softmax(q11arr2))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [42]:
a= np.array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]])

b= np.array([[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]])

In [44]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [45]:
start_date=np.datetime64("2020-09-15")
end_date=np.datetime64("2020-09-25")
np.arange(start_date, end_date)

array(['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
       '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
       '2020-09-23', '2020-09-24'], dtype='datetime64[D]')

### `Q-14:` Subtract the mean of each row from a matrix.

In [51]:
q14arr=np.random.randint(1,10,(3,3))
mean_array=np.mean(q14arr, axis=1)
q14arr-mean_array

array([[-3.33333333,  2.66666667,  6.66666667],
       [-3.33333333,  1.66666667,  4.66666667],
       [-5.33333333, -5.33333333,  1.66666667]])

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [52]:
q15arr=np.random.randint(1,10,(3,3))
display(q15arr)
q15arr[:,1],q15arr[:,2]=q15arr[:,2].copy(),q15arr[:,1].copy()
display(q15arr)


array([[7, 6, 4],
       [9, 7, 6],
       [3, 6, 1]])

array([[7, 4, 6],
       [9, 6, 7],
       [3, 1, 6]])

### `Q-16:` Replace odd elements in arrays with -1.

In [54]:
q16arr=np.random.randint(1,10,(3,3))
q16arr

array([[1, 2, 2],
       [9, 1, 5],
       [1, 1, 2]])

In [57]:
q16arr[np.where(q16arr%2!=0)]=-1

In [58]:
q16arr

array([[-1,  2,  2],
       [-1, -1, -1],
       [-1, -1,  2]])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [59]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

In [60]:
np.maximum(a,b)

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [61]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 419, 6362, 8669, 1904, 8033],
       [5494, 2988, 6669, 2756, 1508],
       [9310, 9747, 1806, 2125, 8532],
       [5127,  989, 2817, 9388, 1804],
       [4544, 4249, 6389, 1760, 5077],
       [2302, 7547, 5207, 4093, 3185],
       [9899, 2386, 2502, 3715,   93],
       [6905, 9582,  190, 4662, 6831]])

In [62]:
arr1[:,::2]

array([[ 419, 8669, 8033],
       [5494, 6669, 1508],
       [9310, 1806, 8532],
       [5127, 2817, 1804],
       [4544, 6389, 5077],
       [2302, 5207, 3185],
       [9899, 2502,   93],
       [6905,  190, 6831]])

In [72]:
(arr1-arr1.min())/(arr1.max()-arr1.min())

array([[0.03324495, 0.63930247, 0.87456659, 0.18468285, 0.80970834],
       [0.55078523, 0.29522741, 0.67060983, 0.27156843, 0.14429941],
       [0.93993473, 0.98449929, 0.17468897, 0.20722007, 0.86059555],
       [0.51335917, 0.09137263, 0.27778911, 0.94788905, 0.17448501],
       [0.45390577, 0.42382215, 0.64205588, 0.16999796, 0.50826025],
       [0.22527024, 0.76014685, 0.52151744, 0.40791352, 0.31531715],
       [1.        , 0.23383643, 0.24566592, 0.36936569, 0.        ],
       [0.69467673, 0.96767285, 0.0098919 , 0.46593922, 0.68713033]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [77]:
q19arr=np.array([12,34,40,7,1,0])
q19arr.sort()
q19arr[-3]

12

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [87]:
a = np.array([1,2,3])
b=a.repeat(3)
c=np.tile(a,3)

d=np.concatenate((b,c ))
d

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])